name = "remote-mcp-server-authless"
main = "src/index.ts"
compatibility_date = "2024-09-24"
account_id = "1bc7cb077d8e12606d26d0afb422056d"

[vars]
# Add any environment variables your worker needs here
# Ex: DB_URL = "your-database-url"

[env.production]
name = "remote-mcp-server-authless"
# Production-specific vars can go here

[env.preview]
# Preview-specific vars can go here
