name: Deploy Main Worker

on:
  push:
    branches:
      - main
    paths:
      - 'packages/worker/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Main Production Worker
    steps:
      - name: Log Workflow Version
        run: |
          echo "🔧 Workflow: Deploy Main Worker"
          echo "📅 Version: 2025-10-25-v2 (Fixed secret names to CF_API_TOKEN and CF_ACCOUNT_ID)"
          echo "⏰ Triggered at: $(date -u +"%Y-%m-%d %H:%M:%S UTC")"
      
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: |
          cd packages/worker
          npm install
      
      - name: Deploy Worker to Production
        run: |
          cd packages/worker
          npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

